### ISSUE TITLE
Github code does not match latest JAR

### ISSUE THREAD

**Issue by ryanb93** [jakehschwartz/finatra-swagger#32]
`18.3.1` is the latest version in [maven central](https://mvnrepository.com/artifact/com.jakehschwartz/finatra-swagger_2.12/18.3.1) but the version in Github is `17.11.0`. Please update Github with the latest version of the code.

**Comment by ryanb93** [comment]
@jakehschwartz was this just fixed with that last commit you made?

**Comment by jakehschwartz** [comment]
Yes, it should have been. I started to test against the Finatra 18.4.0 version last night and realized I never committed 18.3.1.

**Comment by jakehschwartz** [comment]
but it looks like there is still an issue with the swagger webjar version. I create 18.3.2 and 18.4.0 versions today.
